"""criacao inicial das tabelas

Revision ID: b262ce047e23
Revises: 
Create Date: 2026-08-13 17:49:09.972251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b262ce047e23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('itens_pedidos', 'pedidos_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_pedidos', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_pedidos'), 'itens_pedidos', type_='foreignkey')
    op.drop_constraint(op.f('fk_produto'), 'itens_pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'itens_pedidos', 'pedidos', ['pedidos_id'], ['id'])
    op.create_foreign_key(None, 'itens_pedidos', 'produto', ['produto_id'], ['id'])
    op.add_column('pedidos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    postgresql.ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'CANCELADO', name='statuspedido').create(op.get_bind(), checkfirst=True)
    op.alter_column('pedidos', 'status', server_default=None)

    op.alter_column('pedidos', 'status',
           existing_type=sa.VARCHAR(length=20),
           type_=sa.Enum('PENDENTE', 'PAGO', 'ENVIADO', 'CANCELADO', name='statuspedido'),
           existing_nullable=False,
           postgresql_using="upper(status)::statuspedido")

    op.alter_column('pedidos', 'status', server_default=sa.text("'PENDENTE'::statuspedido"))
    op.alter_column('pedidos', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_usuarios'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint(op.f('pedidos_status_check'), 'pedidos', type_='check')
    op.drop_column('pedidos', 'usuarios_id')
    op.alter_column('produto', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('produto', 'estoque',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('produto', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuarios', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'cliente'::character varying"))
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('usuarios', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuarios', 'senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuarios', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'cliente'::character varying"))
    op.alter_column('produto', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('produto', 'estoque',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('produto', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('pedidos', sa.Column('usuarios_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('pedidos_status_check'), 'pedidos', "status::text = ANY (ARRAY['pendente'::character varying, 'pago'::character varying, 'enviado'::character varying, 'cancelado'::character varying]::text[])")
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios'), 'pedidos', 'usuarios', ['usuarios_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('pedidos', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pedidos', 'status',
               existing_type=sa.Enum('PENDENTE', 'PAGO', 'ENVIADO', 'CANCELADO', name='statuspedido'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pendente'::character varying"))
    postgresql.ENUM(name='statuspedido').drop(op.get_bind(), checkfirst=True)
    op.drop_column('pedidos', 'usuario_id')
    op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_produto'), 'itens_pedidos', 'produto', ['produto_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_pedidos'), 'itens_pedidos', 'pedidos', ['pedidos_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('itens_pedidos', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_pedidos', 'pedidos_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_pedidos', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
