"""adicionar imagem ao produto

Revision ID: e348e7211928
Revises: 26dc11b4a7ed
Create Date: 2026-10-06 18:50:02.276348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e348e7211928'
down_revision: Union[str, Sequence[str], None] = '26dc11b4a7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('imagem_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'imagem_url')
    # ### end Alembic commands ###
